// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef COMPILE_ODB_HXX
#define COMPILE_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20300UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "compile.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // compile
  //
  template <>
  struct class_traits< ::compile >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::compile >
  {
    public:
    typedef ::compile object_type;
    typedef ::compile* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // compile
  //
  template <typename A>
  struct query_columns< ::compile, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    id_type_;

    static const id_type_ id;

    // user_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    user_id_type_;

    static const user_id_type_ user_id;

    // source_code
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    source_code_type_;

    static const source_code_type_ source_code;

    // result
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    result_type_;

    static const result_type_ result;

    // language
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    language_type_;

    static const language_type_ language;

    // main_class
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    main_class_type_;

    static const main_class_type_ main_class;

    // input
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    input_type_;

    static const input_type_ input;

    // output
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    output_type_;

    static const output_type_ output;

    // time_used
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    time_used_type_;

    static const time_used_type_ time_used;

    // memory_used
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        unsigned int,
        mysql::id_ulong >::query_type,
      mysql::id_ulong >
    memory_used_type_;

    static const memory_used_type_ memory_used;

    // compile_info
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    compile_info_type_;

    static const compile_info_type_ compile_info;
  };

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::id_type_
  query_columns< ::compile, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::user_id_type_
  query_columns< ::compile, id_mysql, A >::
  user_id (A::table_name, "`user_id`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::source_code_type_
  query_columns< ::compile, id_mysql, A >::
  source_code (A::table_name, "`source_code`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::result_type_
  query_columns< ::compile, id_mysql, A >::
  result (A::table_name, "`result`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::language_type_
  query_columns< ::compile, id_mysql, A >::
  language (A::table_name, "`language`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::main_class_type_
  query_columns< ::compile, id_mysql, A >::
  main_class (A::table_name, "`main_class`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::input_type_
  query_columns< ::compile, id_mysql, A >::
  input (A::table_name, "`input`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::output_type_
  query_columns< ::compile, id_mysql, A >::
  output (A::table_name, "`output`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::time_used_type_
  query_columns< ::compile, id_mysql, A >::
  time_used (A::table_name, "`time_used`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::memory_used_type_
  query_columns< ::compile, id_mysql, A >::
  memory_used (A::table_name, "`memory_used`", 0);

  template <typename A>
  const typename query_columns< ::compile, id_mysql, A >::compile_info_type_
  query_columns< ::compile, id_mysql, A >::
  compile_info (A::table_name, "`compile_info`", 0);

  template <typename A>
  struct pointer_query_columns< ::compile, id_mysql, A >:
    query_columns< ::compile, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::compile, id_mysql >:
    public access::object_traits< ::compile >
  {
    public:
    struct id_image_type
    {
      unsigned int id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      unsigned int id_value;
      my_bool id_null;

      // user_id_
      //
      unsigned int user_id_value;
      my_bool user_id_null;

      // source_code_
      //
      unsigned int source_code_value;
      my_bool source_code_null;

      // result_
      //
      unsigned int result_value;
      my_bool result_null;

      // language_
      //
      unsigned int language_value;
      my_bool language_null;

      // main_class_
      //
      details::buffer main_class_value;
      unsigned long main_class_size;
      my_bool main_class_null;

      // input_
      //
      details::buffer input_value;
      unsigned long input_size;
      my_bool input_null;

      // output_
      //
      details::buffer output_value;
      unsigned long output_size;
      my_bool output_null;

      // time_used_
      //
      unsigned int time_used_value;
      my_bool time_used_null;

      // memory_used_
      //
      unsigned int memory_used_value;
      my_bool memory_used_null;

      // compile_info_
      //
      details::buffer compile_info_value;
      unsigned long compile_info_size;
      my_bool compile_info_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 11UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::compile, id_common >:
    public access::object_traits_impl< ::compile, id_mysql >
  {
  };

  // compile
  //
}

#include "compile-odb.ixx"

#include <odb/post.hxx>

#endif // COMPILE_ODB_HXX
