// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "compile-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // compile
  //

  struct access::object_traits_impl< ::compile, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::compile, id_mysql >::id_type
  access::object_traits_impl< ::compile, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::compile, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // user_id_
    //
    t[1UL] = 0;

    // source_code_
    //
    t[2UL] = 0;

    // result_
    //
    t[3UL] = 0;

    // language_
    //
    t[4UL] = 0;

    // main_class_
    //
    if (t[5UL])
    {
      i.main_class_value.capacity (i.main_class_size);
      grew = true;
    }

    // input_
    //
    if (t[6UL])
    {
      i.input_value.capacity (i.input_size);
      grew = true;
    }

    // output_
    //
    if (t[7UL])
    {
      i.output_value.capacity (i.output_size);
      grew = true;
    }

    // time_used_
    //
    t[8UL] = 0;

    // memory_used_
    //
    t[9UL] = 0;

    // compile_info_
    //
    if (t[10UL])
    {
      i.compile_info_value.capacity (i.compile_info_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::compile, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // user_id_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.user_id_value;
    b[n].is_null = &i.user_id_null;
    n++;

    // source_code_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.source_code_value;
    b[n].is_null = &i.source_code_null;
    n++;

    // result_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.result_value;
    b[n].is_null = &i.result_null;
    n++;

    // language_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.language_value;
    b[n].is_null = &i.language_null;
    n++;

    // main_class_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.main_class_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.main_class_value.capacity ());
    b[n].length = &i.main_class_size;
    b[n].is_null = &i.main_class_null;
    n++;

    // input_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.input_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.input_value.capacity ());
    b[n].length = &i.input_size;
    b[n].is_null = &i.input_null;
    n++;

    // output_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.output_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.output_value.capacity ());
    b[n].length = &i.output_size;
    b[n].is_null = &i.output_null;
    n++;

    // time_used_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.time_used_value;
    b[n].is_null = &i.time_used_null;
    n++;

    // memory_used_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.memory_used_value;
    b[n].is_null = &i.memory_used_null;
    n++;

    // compile_info_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.compile_info_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.compile_info_value.capacity ());
    b[n].length = &i.compile_info_size;
    b[n].is_null = &i.compile_info_null;
    n++;
  }

  void access::object_traits_impl< ::compile, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::compile, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o.id_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.id_value, is_null, v);
      i.id_null = is_null;
    }

    // user_id_
    //
    {
      unsigned int const& v =
        o.user_id_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.user_id_value, is_null, v);
      i.user_id_null = is_null;
    }

    // source_code_
    //
    {
      unsigned int const& v =
        o.source_code_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.source_code_value, is_null, v);
      i.source_code_null = is_null;
    }

    // result_
    //
    {
      unsigned int const& v =
        o.result_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.result_value, is_null, v);
      i.result_null = is_null;
    }

    // language_
    //
    {
      unsigned int const& v =
        o.language_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.language_value, is_null, v);
      i.language_null = is_null;
    }

    // main_class_
    //
    {
      ::std::string const& v =
        o.main_class_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.main_class_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.main_class_value,
        size,
        is_null,
        v);
      i.main_class_null = is_null;
      i.main_class_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.main_class_value.capacity ());
    }

    // input_
    //
    {
      ::std::string const& v =
        o.input_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.input_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.input_value,
        size,
        is_null,
        v);
      i.input_null = is_null;
      i.input_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.input_value.capacity ());
    }

    // output_
    //
    {
      ::std::string const& v =
        o.output_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.output_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.output_value,
        size,
        is_null,
        v);
      i.output_null = is_null;
      i.output_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.output_value.capacity ());
    }

    // time_used_
    //
    {
      unsigned int const& v =
        o.time_used_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.time_used_value, is_null, v);
      i.time_used_null = is_null;
    }

    // memory_used_
    //
    {
      unsigned int const& v =
        o.memory_used_;

      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.memory_used_value, is_null, v);
      i.memory_used_null = is_null;
    }

    // compile_info_
    //
    {
      ::std::string const& v =
        o.compile_info_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.compile_info_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.compile_info_value,
        size,
        is_null,
        v);
      i.compile_info_null = is_null;
      i.compile_info_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.compile_info_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::compile, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      unsigned int& v =
        o.id_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // user_id_
    //
    {
      unsigned int& v =
        o.user_id_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.user_id_value,
        i.user_id_null);
    }

    // source_code_
    //
    {
      unsigned int& v =
        o.source_code_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.source_code_value,
        i.source_code_null);
    }

    // result_
    //
    {
      unsigned int& v =
        o.result_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.result_value,
        i.result_null);
    }

    // language_
    //
    {
      unsigned int& v =
        o.language_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.language_value,
        i.language_null);
    }

    // main_class_
    //
    {
      ::std::string& v =
        o.main_class_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.main_class_value,
        i.main_class_size,
        i.main_class_null);
    }

    // input_
    //
    {
      ::std::string& v =
        o.input_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.input_value,
        i.input_size,
        i.input_null);
    }

    // output_
    //
    {
      ::std::string& v =
        o.output_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.output_value,
        i.output_size,
        i.output_null);
    }

    // time_used_
    //
    {
      unsigned int& v =
        o.time_used_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.time_used_value,
        i.time_used_null);
    }

    // memory_used_
    //
    {
      unsigned int& v =
        o.memory_used_;

      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_value (
        v,
        i.memory_used_value,
        i.memory_used_null);
    }

    // compile_info_
    //
    {
      ::std::string& v =
        o.compile_info_;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.compile_info_value,
        i.compile_info_size,
        i.compile_info_null);
    }
  }

  void access::object_traits_impl< ::compile, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          unsigned int,
          mysql::id_ulong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::compile, id_mysql >::persist_statement[] =
  "INSERT INTO `compile` "
  "(`id`, "
  "`user_id`, "
  "`source_code`, "
  "`result`, "
  "`language`, "
  "`main_class`, "
  "`input`, "
  "`output`, "
  "`time_used`, "
  "`memory_used`, "
  "`compile_info`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::compile, id_mysql >::find_statement[] =
  "SELECT "
  "`compile`.`id`, "
  "`compile`.`user_id`, "
  "`compile`.`source_code`, "
  "`compile`.`result`, "
  "`compile`.`language`, "
  "`compile`.`main_class`, "
  "`compile`.`input`, "
  "`compile`.`output`, "
  "`compile`.`time_used`, "
  "`compile`.`memory_used`, "
  "`compile`.`compile_info` "
  "FROM `compile` "
  "WHERE `compile`.`id`=?";

  const char access::object_traits_impl< ::compile, id_mysql >::update_statement[] =
  "UPDATE `compile` "
  "SET "
  "`user_id`=?, "
  "`source_code`=?, "
  "`result`=?, "
  "`language`=?, "
  "`main_class`=?, "
  "`input`=?, "
  "`output`=?, "
  "`time_used`=?, "
  "`memory_used`=?, "
  "`compile_info`=? "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::compile, id_mysql >::erase_statement[] =
  "DELETE FROM `compile` "
  "WHERE `id`=?";

  const char access::object_traits_impl< ::compile, id_mysql >::query_statement[] =
  "SELECT "
  "`compile`.`id`, "
  "`compile`.`user_id`, "
  "`compile`.`source_code`, "
  "`compile`.`result`, "
  "`compile`.`language`, "
  "`compile`.`main_class`, "
  "`compile`.`input`, "
  "`compile`.`output`, "
  "`compile`.`time_used`, "
  "`compile`.`memory_used`, "
  "`compile`.`compile_info` "
  "FROM `compile`";

  const char access::object_traits_impl< ::compile, id_mysql >::erase_query_statement[] =
  "DELETE FROM `compile`";

  const char access::object_traits_impl< ::compile, id_mysql >::table_name[] =
  "`compile`";

  void access::object_traits_impl< ::compile, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = static_cast< id_type > (st.id ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::compile, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::compile, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::compile, id_mysql >::pointer_type
  access::object_traits_impl< ::compile, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::compile, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::compile, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::compile, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::compile, id_mysql >::object_type >
  access::object_traits_impl< ::compile, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::compile, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
